  mssql:
    build:
      context: blocks/mssql/build
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password!
      MSSQL_PID: Developer
      MSSQL_DATABASE: grafana
      MSSQL_USER: grafana
      MSSQL_PASSWORD: Password!
    ports:
      - "1433:1433"

  fake-mssql-data:
    image: grafana/fake-data-gen
    network_mode: bridge
    environment:
      FD_DATASOURCE: mssql
      FD_PORT: 1433