  prometheus:
    build: docker/blocks/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      --enable-feature=remote-write-receiver
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.config.file=/etc/prometheus/web.yml

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9101:9100"

  fake-prometheus-data:
    image: grafana/fake-data-gen
    ports:
      - "9091:9091"
    environment:
      FD_DATASOURCE: prom

  alertmanager:
    image: prom/alertmanager 
    volumes:
    - ${PWD}/docker/blocks/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: >
      --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  prometheus-random-data:
    build: docker/blocks/prometheus_random_data
    ports:
      - "8081:8080"

  prometheus-high-card:
    build: docker/blocks/prometheus_high_card
    ports:
      - "9111:9111"

  prometheus-utf8:
    build: docker/blocks/prometheus_utf8
    ports:
      - "9112:9112"
