[run]
init_cmds = [
  ["make","GO_BUILD_DEV=1", "build-go"],
  ["make", "gen-jsonnet"],
  ["./bin/grafana", "server", "-profile", "-profile-addr=127.0.0.1", "-profile-port=6000", "-profile-block-rate=1", "-profile-mutex-rate=5", "-packaging=dev", "cfg:app_mode=development"]
]
watch_all = true
follow_symlinks = true
watch_dirs = [
  "$WORKDIR/apps",
  "$WORKDIR/pkg",
  "$WORKDIR/public/views",
  "$WORKDIR/conf",
  "$WORKDIR/devenv/dev-dashboards",
]
watch_exts = [".go", ".ini", ".toml", ".template.html"]
ignore_files = [".*_gen.go"]
build_delay = 1500
cmds = [
  ["make", "GO_BUILD_DEV=1", "build-go"],
  ["make", "gen-jsonnet"],
  ["./bin/grafana", "server", "-profile", "-profile-addr=127.0.0.1", "-profile-port=6000", "-profile-block-rate=1", "-profile-mutex-rate=5", "-packaging=dev", "cfg:app_mode=development"]
]
