[run]
init_cmds = [
  ["go", "build", "-o", "./bin/grafana-server"],
	["./bin/grafana-server"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/pkg",
	"$WORKDIR/public/views",
	"$WORKDIR/conf",
]
watch_exts = [".go", ".ini", ".toml"]
build_delay = 1500
cmds = [
  ["go", "build", "-o", "./bin/grafana-server"],
	["./bin/grafana-server"]
]
