nginxproxy:
  image: nginx
  ports:
    - "10081:10081"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  command: [nginx-debug, '-g', 'daemon off;']

grafana:
  image: grafana/grafana:${grafana_version}
  ports:
    - "3000:3000"
  environment:
    - GF_SERVER_ROOT_URL=http://localhost:10081

swagger-editor:
  image: swaggerapi/swagger-editor
  ports:
    - "8080:8080"
  volumes:
    - .:/tmp
  environment:
    - SWAGGER_FILE=/tmp/merged.json
