
  # k3s:
  #   image: "rancher/k3s:${K3S_VERSION:-latest}"
  #   command: 
  #   - server
  #   tmpfs:
  #   - /run
  #   - /var/run
  #   privileged: true
  #   environment:
  #   #- K3S_TOKEN=secret
  #   - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
  #   - K3S_KUBECONFIG_MODE=666
  #   volumes:
  #   - .:/output
  #   ports:
  #   - 6443:6443

  sql:
    image: arm64v8/mysql:oracle
    environment:
      MYSQL_ROOT_PASSWORD: grafana
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana
    ports:
      - "3306:3306"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all]
    volumes:
      - ./docker/blocks/hgmt/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  stack24:
    image: grafana/grafana:dev-ubuntu
    ports:
      - 3024:3000
    volumes:
      - ./docker/blocks/hgmt/core.ini:/etc/grafana/grafana.ini
    environment:
      HG_STACK_ID: 24
      GF_DATABASE_NAME: stack24
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: sql
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
    links:
      - sql
    depends_on:
      sql:
        condition: service_healthy

  stack25:
    image: grafana/grafana:dev-ubuntu
    ports:
      - 3025:3000
    volumes:
      - ./docker/blocks/hgmt/core.ini:/etc/grafana/grafana.ini
    environment:
      HG_STACK_ID: 25
      GF_DATABASE_NAME: stack25
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: sql
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
    links:
      - sql
    depends_on:
      sql:
        condition: service_healthy

  stack26:
    image: grafana/grafana:dev-ubuntu
    ports:
      - 3026:3000
    volumes:
      - ./docker/blocks/hgmt/core.ini:/etc/grafana/grafana.ini
    environment:
      HG_STACK_ID: 26
      GF_DATABASE_NAME: stack26
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: sql
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
    links:
      - sql
    depends_on:
      sql:
        condition: service_healthy
  
  entity-store:
    image: grafana/grafana:dev-ubuntu
    volumes:
      - ./docker/blocks/hgmt/entity.ini:/etc/grafana/grafana.ini
    links:
      - stack24
      - stack25
      - stack26
      - sql
