  graphite09:
    build: blocks/graphite
    ports:
      - "8080:80"
      - "2003:2003"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  fake-graphite-data:
    image: grafana/fake-data-gen
    network_mode: bridge
    environment:
      FD_DATASOURCE: graphite
      FD_PORT: 2003

