blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/grafana/grafana/discussions/new
    about: Discuss ideas for new features or enhancements
  - name: Questions & Help
    url: https://community.grafana.com
    about: Please ask and answer questions here.
