run:
  timeout: 10m

linters:
  disable-all: true

linters-settings:
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 5
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 5

issues:
  exclude-rules:
    - linters:
        - gosec
      text: G108
    - linters:
        - gosec
      text: G110
    - linters:
        - gosec
      text: G201
    - linters:
        - gosec
      text: G202
    - linters:
        - gosec
      text: G306
    - linters:
        - gosec
      text: G401
    - linters:
        - gosec
      text: G402
    - linters:
        - gosec
      text: G501
