  postgrestest:
    image: postgres:latest
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: grafana
    ports:
      - "5432:5432"
    command: postgres -c log_connections=on -c logging_collector=on -c log_destination=stderr -c log_directory=/var/log/postgresql

  fake-postgres-data:
    image: grafana/fake-data-gen
    network_mode: bridge
    environment:
      FD_DATASOURCE: postgres
      FD_PORT: 5432