name: Start Grafana server
description: Starts a Grafana server for use with e2e tests

inputs:
  package:
    description: A Grafana tar.gz package
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p workspace/grafana
        tar --strip-components=1 -xvf ${{ inputs.package }} -C ./workspace/grafana
    - shell: bash
      run: cp -r devenv scripts tools ./workspace/grafana
    - shell: bash
      run: |
        echo "GRAFANA_HOME=$GITHUB_ACTION_PATH/workspace/grafana" >> $GITHUB_ENV
        ./workspace/grafana/scripts/grafana-server/start-server &
