  mssqltests:
    build:
      context: blocks/mssql/build
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password!
      MSSQL_PID: Express
      MSSQL_DATABASE: grafanatest
      MSSQL_USER: grafana
      MSSQL_PASSWORD: Password!
    ports:
      - "1433:1433"