  mysql:
    image: mysql:${mysql_version}
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_monitor_enable=all
      - --default-authentication-plugin=mysql_native_password
      # Please keep sql-require-primary-key option enabled, to make sure we don't accidentally introduce migration
      # adding new table without PK.
      - --sql-require-primary-key=ON

  fake-mysql-data:
    image: grafana/fake-data-gen
    environment:
      FD_SERVER: mysql
      FD_DATASOURCE: mysql
      FD_PORT: 3306
