# This will proxy all requests for http://localhost:10081/grafana/ to
# http://localhost:3000 (Grafana running locally)
#
# Please note that you'll need to change the root_url in the Grafana configuration:
# root_url = %(protocol)s://%(domain)s:10081/grafana/

  apacheproxy:
    build: docker/blocks/apache_proxy_mac
    ports:
      - "10081:10081"
