on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  gen-swagger:
    name: Alerting Swagger spec generation cron job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set go version
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Build swagger
        run: |
          make -C pkg/services/ngalert/api/tooling post.json api.json
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update alerting swagger spec"
          title: "Alerting: Update Swagger spec"
          body: |
            This is an automated pull request to update the alerting swagger spec.
            Please review and merge.
          branch: update-alerting-swagger-spec
          delete-branch: true
          labels: 'area/alerting,type/docs,no-backport,no-changelog'
          team-reviewers: 'grafana/alerting-backend-product'
          draft: false

