on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  gen-swagger:
    name: Alerting Swagger spec generation cron job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Set go version
        uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639
        with:
          go-version-file: go.mod
      - name: Build swagger
        run: |
          make -C pkg/services/ngalert/api/tooling post.json api.json
          make swagger-clean && make openapi3-gen
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update alerting swagger spec"
          title: "Alerting: Update Swagger spec"
          body: |
            This is an automated pull request to update the alerting swagger spec.
            Please review and merge.
          branch: update-alerting-swagger-spec
          delete-branch: true
          labels: 'area/alerting,type/docs,no-changelog'
          team-reviewers: 'grafana/alerting-backend'
          draft: false
