name: Cloud data sources test code coverage
on:
  pull_request:
    paths:
      - 'pkg/tsdb/azuremonitor/**'
      - 'pkg/tsdb/cloudwatch/**'
      - 'pkg/tsdb/cloudmonitoring/**'
      - 'public/app/plugins/datasource/grafana-azure-monitor-datasource/**'
      - 'public/app/plugins/datasource/cloudwatch/**'
      - 'public/app/plugins/datasource/cloud-monitoring/**'
    branches-ignore:
      - dependabot/**
      - backport-*

jobs:
  workflow-call:
    uses: grafana/code-coverage/.github/workflows/code-coverage.yml@v0.1.10
    with:
      frontend-path-regexp: public\/app\/plugins\/datasource\/(grafana-azure-monitor-datasource|cloud-monitoring|cloudwatch)
      backend-path-regexp: pkg\/tsdb\/(azuremonitor|cloudmonitoring|cloudwatch)
