name: Deploy
#on a push to tags to trigger GitHub action workflow
on:
  push:
    tags:
      - 'dev-**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: configure environment
        uses: actions/checkout@v1
      - name: branch name
        run: echo running on branch dev
      - name: deploy 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/grafana
            git fetch
            git checkout dev
            git pull
            sudo docker-compose down
            sudo docker image rm corewatts-grafana
            sudo docker build -t corewatts-grafana -f Dockerfile .
            sudo docker-compose up -d