name: Deploy pr preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - "docs/sources/**"

jobs:
  deploy-pr-preview:
    if: "!github.event.pull_request.head.repo.fork"
    uses: grafana/writers-toolkit/.github/workflows/deploy-preview.yml@main # zizmor: ignore[unpinned-uses]
    with:
      branch: ${{ github.head_ref }}
      event_number: ${{ github.event.number }}
      repo: grafana
      sha: ${{ github.event.pull_request.head.sha }}
      sources: |
        [
          {
            "index_file": "content/docs/grafana/_index.md",
            "relative_prefix": "/docs/grafana/latest/",
            "repo": "grafana",
            "source_directory": "docs/sources",
            "website_directory": "content/docs/grafana/latest"
          }
        ]
      title: ${{ github.event.pull_request.title }}
