name: Deploy pr preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - "docs/sources/**"

jobs:
  deploy-pr-preview:
    if: github.repository == 'grafana/grafana'
    uses: grafana/writers-toolkit/.github/workflows/deploy-preview.yml@main
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      branch: ${{ github.head_ref }}
      event_number: ${{ github.event.number }}
      title: ${{ github.event.pull_request.title }}
      repo: grafana
      website_directory: content/docs/grafana/latest
      relative_prefix: /docs/grafana/latest/
      index_file: true
