name: "doc-validator"
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:
jobs:
  doc-validator:
    runs-on: "ubuntu-latest"
    container:
      image: "grafana/doc-validator:v2.0.0"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Run doc-validator tool"
        # Only run doc-validator on specific directories.
        run: >
          doc-validator
          --skip-checks='^image-.+$'
          --include='^docs/sources/(?:fundamentals|getting-started|introduction|setup-grafana|upgrade-guide|whatsnew)/.+\.md$'
          ./docs/sources
          /docs/grafana/latest
