on:
  push:
    branches:
      - fusebit-v1.0.0-v8.3.3
name: Tag
jobs:
  tag:
    name: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: fusebit-v1.0.0-v8.3.3
      - name: Version
        run: export FUSEBIT_VERSION=$(cat .fusebit.version.json | jq -r .version)
      - name: Publish Tags
        run: |
          git tag ${FUSEBIT_VERSION} || true
          git push --tags || true
