name: Create or update GitHub release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone (NO v prefix)
      latest:
        required: false
        description: Mark this release as latest (`1`) or not (`0`, default)
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: Create GitHub release (manually invoked)
        uses: grafana/grafana-github-actions-go/github-release@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          version: ${{ inputs.version }}
          metrics_api_key: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
