name: Create or update GitHub release
on:
  workflow_call:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone (NO v prefix)
        type: string
      latest:
        required: false
        default: "0"
        description: Mark this release as latest (`1`) or not (`0`, default)
        type: string
      dry_run:
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone (NO v prefix)
        type: string
      latest:
        required: false
        default: "0"
        description: Mark this release as latest (`1`) or not (`0`, default)
        type: string
      dry_run:
        required: false
        default: false
        type: boolean

permissions:
  # contents: write allows the action(s) to create github releases
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release (manually invoked)
        uses: grafana/grafana-github-actions-go/github-release@main # zizmor: ignore[unpinned-uses]
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          metrics_api_key: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
          latest: ${{ inputs.latest }}
          dry_run: ${{ inputs.dry_run }}
