# This action is responsible for running `go mod tidy` to sync go dependencies.
name: go tidy

on:
  push:
    branches:
    - test-go-tidy-github-action

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
  USERNAME: grafanabot
  EMAIL: bot@grafana.com

jobs:
  go-tidy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout OSS repo
        uses: actions/checkout@v2
        with:
          repository: grafana/grafana
          path: grafana
      -
        name: Checkout enterprise
        uses: actions/checkout@v2
        with:
          repository: grafana/grafana-enterprise
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          path: grafana-enterprise
      -
        name: Copy enterprise bits into OSS repo
        run: |
          cd grafana-enterprise
          git fetch && git checkout $(echo $GITHUB_REF | cut -d'/' -f 3)
          ./dev.sh >/dev/null
      -
        name: Set up Git
        run: |
          cd grafana
          git config user.name ${USERNAME}
          git config user.email ${EMAIL}
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/grafana/grafana.git
      -
        name: Run go mod tidy
        run: |
          cd grafana
          rm -f go.sum
          go mod tidy
      -
        name: Create Pull Request
        uses: dsotirakis/create-pull-request@v3
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          branch: pr-creator
          commit-message: Update go modules
          path: grafana
          title: 'Chore(deps): Update go modules'
          author: grafanabot <bot@grafana.com>
          body: >
            Auto-generated PR to update go modules.
          labels: type/chore
