name: Close Milestone
on:
  workflow_dispatch:
    inputs:
      version_input:
        description: 'The version to be released please respect: major.minor.patch or major.minor.patch-beta<number> format. example: 7.4.3 or 7.4.3-beta1'
        required: true
jobs:
  call-remove-milestone:
    - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
    - uses: grafana/grafana/.github/workflows/remove-milestone.yml@main
      with:
        version_call: ${{ github.event.inputs.version_input }}
      secrets:
        token: ${{ steps.generate_token.outputs.token }}
  call-close-milestone:
    - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
    - uses: grafana/grafana/.github/workflows/close-milestone.yml@main
      with:
        version_call: ${{ github.event.inputs.version_input }}
      secrets:
        token: ${{ steps.generate_token.outputs.token }}
      needs: call-remove-milestone
