name: End-to-end tests for cloud plugins

on:
  pull_request:
    paths:
      - pkg/tsdb/azuremonitor/**
      - public/app/plugins/datasource/azuremonitor/**
      - e2e-playwright/cloud-plugins-suite/azure-monitor.spec.ts
  push:
    branches:
      - main
      - release-*.*.*
    paths:
      - pkg/tsdb/azuremonitor/**
      - public/app/plugins/datasource/azuremonitor/**
      - e2e-playwright/cloud-plugins-suite/azure-monitor.spec.ts

permissions: {}

jobs:
  run-azure-monitor-e2e:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest-16-cores
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: grafana/shared-workflows/actions/login-to-gar@login-to-gar-v0.4.0
        id: login-to-gar
        with:
          registry: "us-docker.pkg.dev"
          environment: "dev"

      - id: pull-docker-image
        run: |
          docker pull us-docker.pkg.dev/grafanalabs-dev/docker-oss-plugin-partnerships-dev/e2e-playwright:latest

      - id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            AZURE_SP_APP_ID=cpp-azure-resourcemanager-credentials:application_id
            AZURE_SP_PASSWORD=cpp-azure-resourcemanager-credentials:application_secret
            AZURE_TENANT=cpp-azure-resourcemanager-credentials:tenant_id

      - id: deploy-resources
        env:
          AZURE_SP_APP_ID: ${{ env.AZURE_SP_APP_ID}}
          AZURE_SP_PASSWORD: ${{ env.AZURE_SP_PASSWORD}}
          AZURE_TENANT: ${{ env.AZURE_TENANT }}
          NAME: ${{ github.ref_name }}
        run: |
          docker container run --name cpp-e2e-deploy -e AZURE_SP_APP_ID -e AZURE_SP_PASSWORD -e AZURE_TENANT -e PLAYWRIGHT_CI=true us-docker.pkg.dev/grafanalabs-dev/docker-oss-plugin-partnerships-dev/e2e-playwright:latest ./cpp-e2e/scripts/ci-run-playwright.sh azure "${NAME}" deploy

      - id: extract-creds
        # see https://github.com/grafana/oss-plugin-partnerships/blob/a77040d0456003cd258668b61d542dc7c75db5b5/e2e/scripts/deploy.sh#L25 for path
        run: |
          docker cp cpp-e2e-deploy:/outputs.json /tmp/outputs.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build Grafana
        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e
        with:
          verb: run
          args: go run ./pkg/build/cmd artifacts -a targz:grafana:linux/amd64 --grafana-dir="${PWD}" > out.txt

      - name: Run E2E tests
        run: yarn e2e:playwright:cloud-plugins

      - name: Destroy resources
        if: always() && steps.deploy-resources.outcome == 'success'
        env:
          AZURE_SP_APP_ID: ${{ env.AZURE_SP_APP_ID }}
          AZURE_SP_PASSWORD: ${{ env.AZURE_SP_PASSWORD }}
          AZURE_TENANT: ${{ env.AZURE_TENANT }}
          NAME: ${{ github.ref_name }}
        run: |
          docker container run --name cpp-e2e-destroy -e AZURE_SP_APP_ID -e AZURE_SP_PASSWORD -e AZURE_TENANT us-docker.pkg.dev/grafanalabs-dev/docker-oss-plugin-partnerships-dev/e2e-playwright:latest ./cpp-e2e/scripts/ci-run-playwright.sh azure "${NAME}" destroy
