name: "publish-kinds-next"

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/sources/**"
  workflow_dispatch:

jobs:
  sync:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Grafana repo"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version: '1.19.2'

      - name: "Verify kinds"
        run: go run .github/workflows/scripts/kinds/verify-kinds.go
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: "Clone website-sync Action"
        # WEBSITE_SYNC_TOKEN is a fine-grained GitHub Personal Access Token that expires.
        # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
        # GitHub administrator to update the organization secret.
        # The IT helpdesk can update the organization secret.
        run: "git clone --single-branch --no-tags --depth 1 -b master https://grafanabot:${{ secrets.WEBSITE_SYNC_TOKEN }}@github.com/grafana/website-sync ./.github/actions/website-sync"

      - name: "Publish to kind registry (next)"
        uses: "./.github/actions/website-sync"
        id: "publish-next"
        with:
          repository: "grafana/kind-registry"
          branch: "main"
          host: "github.com"
          # PUBLISH_TO_KIND_REGISTRY_TOKEN is a fine-grained GitHub Personal Access Token that expires.
          # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
          # GitHub administrator to update the organization secret.
          # The IT helpdesk can update the organization secret.
          github_pat: "grafanabot:${{ secrets.PUBLISH_TO_KIND_REGISTRY_TOKEN }}"
          source_folder: ".github/workflows/scripts/kinds/next"
          target_folder: "grafana/next"
