name: Run dashboard scenes e2e

on:
  schedule:
    - cron: "0 8 * * 1-5" # every day at 08:00UTC on weekdays
  # push # uncomment for test run during PR

env:
  ARCH: linux-amd64

jobs:
  dashboard-scenes-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pin Go version to mod file
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build grafana
        run: make build
      - name: Install Cypress dependencies
        uses: cypress-io/github-action@v6
        with: 
          runTests: false
      - name: Run dashboard scenes e2e
        run: yarn e2e:scenes
      - name: "Send Slack notification"
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: >
            {
              "icon_emoji": ":this-is-fine-fire:",
              "username": "Dashboard scenes e2e tests failed",
              "text": "Link to run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
              "channel": "#grafana-dashboards-squad"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
