name: Update changelog
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Needs to match, exactly, the name of a milestone. The version to be released please respect: major.minor.patch, major.minor.patch-preview or major.minor.patch-preview<number> format. example: 7.4.3, 7.4.3-preview or 7.4.3-preview1'
      skip_pr:
        required: false
        default: "0"
      skip_community_post:
        required: false
        default: "0"
jobs:
  config:
    runs-on: "ubuntu-latest"
    outputs:
      has-secrets: ${{ steps.check.outputs.has-secrets }}
    steps:
      - name: "Check for secrets"
        id: check
        shell: bash
        run: |
          if [ -n "${{ (secrets.GRAFANA_DELIVERY_BOT_APP_ID != '' &&
                        secrets.GRAFANA_DELIVERY_BOT_APP_PEM != '' &&
                        secrets.GRAFANA_MISC_STATS_API_KEY != '' &&
                        secrets.GRAFANABOT_FORUM_KEY != ''
                        ) || '' }}" ]; then
            echo "has-secrets=1" >> "$GITHUB_OUTPUT"
          fi

  main:
    needs: config
    if: needs.config.outputs.has-secrets
    runs-on: ubuntu-latest
    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - name: Run update changelog (manually invoked)
        uses: grafana/grafana-github-actions-go/update-changelog@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          version: ${{ inputs.version }}
          metrics_api_key: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
          community_api_key: ${{ secrets.GRAFANABOT_FORUM_KEY }}
          community_api_username: grafanabot
          skip_pr: ${{ inputs.skip_pr }}
          skip_community_post: ${{ inputs.skip_community_post }}
