global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: grafana
    always_scrape_classic_histograms: true
    static_configs:
      - targets:
          - host.docker.internal:3000
